[package]
name = "wstr_macro"
version = "0.1.0"
#edition = '2018'
license = "ISC"
authors = ["VukoDrakkeinen <sneyk8+git@gmail.com>"]
publish = false
workspace = ".."

[lib]
proc-macro = true

[dependencies]
syn = "^0.15.33"
quote = "^0.6.12"
